Added IN_VOTER test case
NCATComp410/comp410_fall_2024 pull request #47
Opened 2024-10-29 18:29 UTC by danabrunson

2024-10-29 19:22 UTC, cgboyce approved these changes

2024-10-31 22:56 UTC, claesmk commented on test_team_tech_baddies.py
> +                # Check no context
voter is a context word for IN_VOTER according to the [opensource](https://github.com/microsoft/presidio/blob/cc31bb61982311d7e2ad7e3b5334da797cdb6f98/presidio-analyzer/presidio_analyzer/predefined_recognizers/in_voter_recognizer.py#L37) - so I don't see how this is a check for no context as stated in the comment.

2024-10-31 22:57 UTC, claesmk requested changes
I would suggest improving the no context case as noted.

2024-11-01 00:26 UTC, claesmk approved these changes
You missed what I was saying about context words.  I made the change for you

2024-11-02 00:51 UTC, claesmk commented
Is this a duplicate of #48 ? which one is correct?

2024-11-03 17:02 UTC, merged