Added IP_Address test cases
NCATComp410/comp410_fall_2024 pull request #56
Opened 2024-10-31 20:07 UTC by Pojohnson-XJ

2024-10-31 21:10 UTC, ZachLCOMP approved these changes
Looks pretty good to me. All tests are passing

2024-10-31 23:23 UTC, claesmk commented on test_team_1.py
> +        net2 = ['243', '542', '495']  #Second part of the IP Address
542 and 495 are not valid octets

2024-10-31 23:24 UTC, claesmk commented on test_team_1.py
> +                        break
You are not actually testing anyting here, only printing the results.  You need an appropriate self.assert() statement to actually test something.

2024-10-31 23:25 UTC, claesmk commented on test_team_1.py
> +                print(result2)
Similar comment here - needs a valid self.assert() statement

2024-10-31 23:25 UTC, claesmk requested changes
Please update the positive test cases as noted

2024-11-01 00:29 UTC, claesmk approved these changes
Looks OK now

2024-11-01 00:30 UTC, merged