ADDED FISCAL CODE
NCATComp410/comp410_fall_2024 pull request #63
Opened 2024-10-31 21:56 UTC by KennyH1886

2024-10-31 22:00 UTC, mawdogbe requested changes
Separate your w/out context and invalid fiscal code test cases and ensure you have the correct score when you run without context. You will need 3 separate test cases. Also be sure to move your test cases to the correct section.

2024-10-31 22:05 UTC, mawdogbe approved these changes
Changes look good, nice test cases.

2024-10-31 22:11 UTC, mawdogbe requested changes
Test cases look good for the most part, please fix your build errors.

2024-10-31 22:16 UTC, mawdogbe approved these changes

2024-11-01 00:18 UTC, claesmk approved these changes
You found a bug in Presidio - "codice fiscale" is not being detected as a context enhancement.  This is because the string is tokenized to a list ['codice', 'fiscale'] we can open a bug against Presido for this next sprint.

2024-11-02 00:56 UTC, claesmk commented
@KennyH1886 are you going to assign this to yourself and merge?

2024-11-02 00:58 UTC, KennyH1886 commented
Yes ! I was making sure I was able to , I’ll get right to that soon.

On Fri, Nov 1, 2024 at 8:56 PM claesmk ***@***.***> wrote:

> @KennyH1886 <https://github.com/KennyH1886> are you going to assign this
> to yourself and merge?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NCATComp410/comp410_fall_2024/pull/63#issuecomment-2452773373>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASTO2UDFNUORMLIXARBGXFLZ6QPMFAVCNFSM6AAAAABQ7GK4RGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJSG43TGMZXGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-12 03:29 UTC, merged